language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - libsystemd-dev

before_install:
  - pip install -r requirements.txt
  - pip install Cython

install:
  - python setup.py install

script:
  - cd tests && python -m unittest discover
